name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Use bash so the same commands work on Windows as well
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi
          # tooling for linting & testing
          python -m pip install flake8 pytest

      - name: Lint with flake8
        shell: bash
        run: |
          # Fail fast on syntax errors / undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Treat style issues as warnings (does not fail the job). Remove --exit-zero if you want lint failures to fail the job.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        shell: bash
        run: |
          pytest
